echo "________________________________________________________________________________"
echo "Installing and configuring zsh:\n"
brew install zsh zsh-completions
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
ln -s "$HOME/.zprezto/runcoms/zlogin" "$HOME/.zlogin" 
ln -s "$HOME/.zprezto/runcoms/zlogout" "$HOME/.zlogout"
ln -s "$HOME/.zprezto/runcoms/zpreztorc" "$HOME/.zpreztorc"
ln -s "$HOME/.zprezto/runcoms/zprofile" "$HOME/.zprofile"
ln -s "$HOME/.zprezto/runcoms/zshenv" "$HOME/.zshenv"
ln -s "$HOME/.zprezto/runcoms/zshrc" "$HOME/.zshrc"
## General stuff to the zsh:
echo "export PATH=$HOME/bin:$PATH" >> "$HOME/.zshrc"
echo "export CLICOLOR=1" >> "$HOME/.zshrc"
echo "export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx" >> "$HOME/.zshrc"
echo "export LC_CTYPE=en_US.UTF-8" >> "$HOME/.zshrc"
echo "export LC_ALL=en_US.UTF-8" >> "$HOME/.zshrc"
echo "export tz=CET" >> "$HOME/.zshrc"
echo "export TZ=CET" >> "$HOME/.zshrc"
echo "alias R='R --no-save'" >> "$HOME/.zshrc"
echo 'export PERL5LIB="$PERL5LIB:~/ensembl/API/bioperl-live/:~/ensembl/API/ensembl/modules/:~/ensembl/API/ensembl-compara/modules/:~/ensembl/API/ensembl-funcgen/modules/:~/ensembl/API/ensembl-io/modules/:~/ensembl/API/ensembl-variation/modules/"' >> "$HOME/.zshrc"
