* Installation of owncloud on raspberry

Some links:


Point is that debian does no longer support/distribute owncloud.

#+BEGIN_EXAMPLE
  sudo su
  echo 'deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' > /etc/apt/sources.list.d/owncloud.list
  cd /tmp
  wget -nv https://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.key -O Release.key
  sudo apt-key add - < Release.key
#+END_EXAMPLE

Install mariadb

#+BEGIN_EXAMPLE
  sudo apt-get install mariadb-client mariadb-server
  ## enable at startup
  sudo update-rc.d mysql defaults
  sudo mysql_install_db
  sudo service mysql start
  sudo mysql_secure_installation
#+END_EXAMPLE

Now connect to the database and add users.

#+BEGIN_EXAMPLE
  create user 'jo'@'localhost' identified by '<pass>';
  grant all privileges on *.* to 'jo'@'localhost';
#+END_EXAMPLE

Install owncloud

This is following
https://doc.owncloud.org/server/10.0/admin_manual/installation/source_installation.html
and https://www.howtoforge.com/tutorial/owncloud-install-debian-8-jessie/
and https://raspberry.tips/raspberrypi-tutorials/owncloud-10-server-auf-dem-raspberry-pi
to install the newest version.

#+BEGIN_EXAMPLE
  sudo apt-get install apt-transport-https lsb-release ca-certificates
  sudo apt-get install owncloud owncloud-apps
#+END_EXAMPLE

Install the latest owncloud release:

#+BEGIN_EXAMPLE
  cd ~
  wget https://download.owncloud.org/community/owncloud-10.0.2.tar.bz2
  tar xjf owncloud-*
#+END_EXAMPLE

backup /etc/owncloud first, copy the folder over to */usr/share/owncloud*.

stop apache2:

#+BEGIN_EXAMPLE
  sudo service apache2 stop
#+END_EXAMPLE

Fix rights:

#+BEGIN_EXAMPLE
  sudo find /usr/share/owncloud/ -type f -print0 | sudo xargs -0 chmod 0640
  sudo find /usr/share/owncloud/ -type d -print0 | sudo xargs -0 chmod 0750
  sudo chown -R root:www-data /usr/share/owncloud/
  sudo chown -R www-data:www-data /usr/share/owncloud/apps/
  sudo chown -R www-data:www-data /usr/share/owncloud/config/
  sudo chown -R www-data:www-data /usr/share/owncloud/themes/
  sudo chown root:www-data /usr/share/owncloud/.htaccess
  sudo chmod 0644 /usr/share/owncloud/.htaccess
#+END_EXAMPLE

start apache again

#+BEGIN_EXAMPLE
  sudo service apache2 start
#+END_EXAMPLE

Create an =owncloud= user and =owncloud= database:

#+BEGIN_EXAMPLE
  mysql -h localhost -u root -p
#+END_EXAMPLE

Then create the owncloud db and user

#+BEGIN_EXAMPLE
  create database owncloud;
  create user 'owni'@'localhost' identified by 'yo_mama';
  grant all privileges on owncloud.* to 'owni'@'localhost';
#+END_EXAMPLE

Check config.php:

#+BEGIN_EXAMPLE
  'trusted_domains' =>.
  array (
    0 => '192.168.13.14',
    1 => 'johome.asuscomm.com',
  ),  
#+END_EXAMPLE

Configure apache:

Copy the following to =/etc/apache2/conf-available/owncloud.conf= and make a
symlink to =conf-enabled= - or edit the already existing one there.

#+BEGIN_EXAMPLE
  Alias /owncloud "/var/www/owncloud/"

  <Directory /var/www/owncloud/>
    Options +FollowSymlinks
    AllowOverride All

   <IfModule mod_dav.c>
    Dav off
   </IfModule>

   SetEnv HOME /var/www/owncloud
   SetEnv HTTP_HOME /var/www/owncloud

  </Directory>
#+END_EXAMPLE

Enable additions modules:

#+BEGIN_EXAMPLE
  sudo a2enmod rewrite
  sudo a2enmod headers
  sudo a2enmod env
  sudo a2enmod dir
  sudo a2enmod mime
  sudo a2enmod ssl
  sudo a2ensite default-ssl
  sudo service apache2 restart
#+END_EXAMPLE

Configure owncloud via web.


* Installation of nextcloud

Check also http://ifahrentholz.de/2016/install-nextcloud-on-raspberry/

#+BEGIN_EXAMPLE
  sudo echo 'deb http://apt.jurisic.org/debian/ jessie main contrib non-free' >> /etc/apt/sources.list.d/nextcloud.list
  wget -q http://apt.jurisic.org/Release.key -O- | apt-key add -
  
#+END_EXAMPLE

Install required stuff.

#+BEGIN_EXAMPLE
  sudo apt-get update
  sudo apt-get install nextcloud
#+END_EXAMPLE


