* Installing ArchLabs

** Installation

To update/sync the repos: =pacman -Sy=.
Generally, use =pacman -Ss <pkgname>= to search for a package, it is also possible
to search using =pkgfile <file within package>=.

+ Setup the system using: =sudo ./archlinux-install.sh=.
+ To install additional stuff from AUR use =./archlinux-install-aur.sh=. This
  needs user interaction and *should not* be run as su.
+ Set up the zsh: =./zsh-config.sh=.
+ Install perl: =./arch-install-perl.sh=. After installation finished exit the
  shell so the installation completes (somehow gets stuck). To make the new perl
  default use =perlbrew list= and =perlbrew switch= to switch.
+ Install R: =./install-R-release.sh=.
+ Install all gits: =./install-gits.sh=.
+ Set up all paths and environment variables in =~/.zshrc=:
  #+BEGIN_EXAMPLE
    ## Alias
    alias mc="mc --nosubshell"
  #+END_EXAMPLE

*** Emacs

Install settings using /https://github.com/jotsetung/memacs/. After that, copy the
/linux.emacs/ file to the home dir and all should be fine.


*** MySQL setup

1) Install databases: =sudo mysql_install_db --user=mysql --basedir=/usr
   --datadir=/var/lib/mysql=.
2) Start database: =sudo /usr/bin/mysqld_safe &=.
3) Set root password etc =/usr/bin/mysql_secure_installation=.
4) Add user: =create user 'jo'@'localhost' identified by '<pass>';= and grant
   privileges: =grant all privileges on *.* to 'jo'@'localhost';=.


*** VMware

We will need the =unlocker= tool from DrDonk (cloned from github). Run
=lnx-install.sh= with =sudo= to patch vmware.

To enable the vmware services (at boot) we have to do:

#+BEGIN_EXAMPLE
  sudo systemctl enable vmware-networks.service
  sudo systemctl enable vmware-usbarbitrator.service
#+END_EXAMPLE

To just start them use =start= instead of =enable=.

To create a new macOS virtual machine:
- create the virtual machine in macOS (or in linux, if the installer app is
  converted to an iso).
- copy it over to linux.
- edit the =vmx= file by adding =smc.version = "0"=.
- Increase the disk size inside macOS using: =sudo diskutil resizeVolume / R=.
- Install VMWare tools in the virtual machine: attach the iso image that can be
  found at =/usr/lib/vmware/isoimages= to the virtual machine (=darwin.iso= for
  macOS). These tools are updated with the =lnx-update-tools.sh= script of the
  =unlocker= repo. Eventually the tools have to be installed twice.

** Search/install additional stuff

https://aur.archlinux.org/packages

** Customization and setup

*** Zsh

Presto modules, edit =.zpreztorc=:
#+BEGIN_EXAMPLE
  # Set the Prezto modules to load (browse modules).
  # The order matters.
  zstyle ':prezto:load' pmodule \
    'environment' \
    'terminal' \
    'editor' \
    'history' \
    'directory' \
    'spectrum' \
    'utility' \
    'completion' \
    'git' \
    'syntax-highlighting' \
    'prompt'
#+END_EXAMPLE

*** General stuff

To increase the size of the =/tmp= directory: edit =/etc/fstab=:
#+BEGIN_EXAMPLE
  tmpfs	/tmp	tmpfs	rw,nodev,nosuid,size=4G	0 0
#+END_EXAMPLE

*** Useful shortcuts:

+ Disable =C-space=: edit =~/.config/openbox/rc.xml, search for /C-space/ and
  comment it out.
+ Add shortcut for desktop switching:
  #+BEGIN_EXAMPLE
    <keybind key="W-A-Left">
      <action name="GoToDesktop">
	<to>left</to>
	<wrap>no</wrap>
      </action>
    </keybind>
    <keybind key="W-A-Right">
      <action name="GoToDesktop">
	<to>right</to>
	<wrap>no</wrap>
      </action>
    </keybind>
  #+END_EXAMPLE

+ =W-1=: go to desktop 1 (same for 2...).
+ =W-f=: open file manager.
+ =W-t=: open terminal.
+ =W-W=: open program list.
+ =W-space=: open menu.
+ =W+Left=: left maximize.
+ =W+Right=: right maximize.
+ =A-r=: resize window using arrow keys and hit enter when done.
+ =A-space=: show menu.

*** Retina display/HIDPI

To set HIDPI etc:
https://www.reddit.com/r/linux/comments/6lkmoa/archlabs_50_looks_pretty_special_with_openbox_and/
https://github.com/Dobbie03/dots

1) =.Xresources=: edit that with settings from Dobbie03. Use DPI of 160.
2) =./config/polybar/master.conf=: set =height= to 50 and increase the font sizes
   (e.g. 20).
3) Go to settings, appearance and edit /Custom DPI setting/.
4) Increase font size in =.config/jgmenu/jgmenurc=.
5) Edit =geometry= in =.config/termite/config= (e.g. to 1400x600).

*** Encrypted folders

Folders can be encrypted using =ecryptfs=. To set-up a folder for encryption use
for example:

#+BEGIN_EXAMPLE
  sudo mount -t ecryptfs /home/jo/crypt/EURACrypt2018 /home/jo/crypt/EURACrypt2018
#+END_EXAMPLE

Files can then be copied into the folder and once it is unmounted everything
(except filenames) is encrypted. Note that info on encryption is stored in
root's home!

** Useful commands

- =pacman -Ss <pkgname>=: search for a package.
- =pkgfile <file in package>=: search for a file within a package.
- =pacman -S <pkgname>=: install package.
- =pacman -Sy=: sync package databases.
- =checkupdates=: check updates.
- =pacman -Su=: update.
